
export const PROGRESS_LOADER_SELECTOR = '.MuiCircularProgress-root'
export const NAME_ID_FIELD_SELECTOR = 'div[data-field="nameAndId"]'
export const DOWNLOAD_SECTION_SELECTOR= 'button.MuiButton-containedInfo'
export const HELP_SELECTOR = '#help-button'
export const TABLE_SELECTOR= 'div[role="tablist"]'
export const RECORD_NUMBER_SELECTOR= 'h6.MuiTypography-h6'
export const UPDATE_DATE_SELECTOR = 'h6.MuiTypography-subtitle1'
export const CATALOG_NUMBER_FIELD_SELECTOR= 'div[data-field="catalogNum"]'
export const SEARCH_BAR_SELECTOR= 'div.MuiAutocomplete-fullWidth'
export const SEARCH_INPUT_SELECTOR = 'input[placeholder="Search for catalog number"]'
export const ANTIBPDY_TARGET_FIELD_SELECTOR= 'div[data-field="abTarget"]'
export const USERNAME_SELECTOR = 'input#username'
export const PASSWORD_SELECTOR = 'input#password'
export const LOGIN_BUTTON_SELECTOR = '#kc-login'
export const USERNAME_TITLE_SELECTOR= '.MuiTypography-subtitle2'
export const ADD_SUBMISSION_SELECTOR = 'a[href = "/add"]'
export const SUBMISSION_PROGRESS_BAR_SELECTOR= 'span[role="progressbar"][aria-valuenow="50"]'
export const NEXT_BUTTON_SELECTOR= 'button.MuiButton-textSecondary'
export const INPUT_URL_SELECTOR = 'input[name="url"]'
export const SUBMIT_SELECTOR = 'button[type="submit"]'
export const INPUT_CATALOG_NUMBER_SELECTOR= 'input[name="catalogNumber"]'
export const INPUT_VENDOR_SELECTOR= 'input[name = "vendor"]'
export const INPUT_NAME_SELECTOR = 'input[name = "name"]'
export const INPUT_HOST_SELECTOR = 'input[name = "host"]'
export const INPUT_TARGET_SPECIES_SELECTOR= 'input[name = "targetSpecies"]'
export const INPUT_ANTIBODY_TARGET_SELECTOR= 'input[name = "antibodyTarget"]'
export const CLONALITY_SELECTOR = '#mui-component-select-clonality'
export const CLONALITY_OPTIONS_SELECTOR = 'li[role="option"]'
export const RECOMBINANT_CLONALITY_SELECTOR = 'li[data-value="recombinant"]'
export const INPUT_CLONE_ID_SELECTOR = 'input[name = "cloneID"]'
export const INPUT_ISOTYPE_SELECTOR = 'input[name = "isotype"]'
export const INPUT_CONJUGATE_SELECTOR = 'input[name = "conjugate"]'
export const INPUT_FORMAT_SELECTOR = 'input[name = "format"]'
export const INPUT_UNIPROT_ID_SELECTOR= 'input[name = "uniprotID"]'
export const INPUT_EPITOPE_SELECTOR= 'input[name = "epitope"]'
export const INPUT_APPLICATIONS_SELECTOR = 'input[name = "applications"]'
export const INPUT_COMMENTS_SELECTOR = 'textarea[name = "comments"]'
export const INPUT_CITATION_SELECTOR = 'input[name = "citation"]'
export const SUCCESSFUL_SUBMISSION_SELECTOR= 'h1.MuiTypography-h1'
export const CLOSE_SUBMISSION_SELECTOR= 'svg[data-testid="CloseIcon"]'
export const ANTIBODY_TYPE_SELECTOR= 'button.MuiCardActionArea-root'
export const MY_SUBMISSIONS_SELECTOR = 'button.MuiTab-labelIcon'
export const FILTER_SELECTOR= 'button[aria-label="Select columns"]'
export const FILTER_TABLE_SELECTOR= 'input[placeholder="Column title"]'
export const FILTER_ELEMENTS_SELECTOR = '.MuiTypography-body1'
export const ANTIBODY_ID_FIELD_SELECTOR= 'div[data-field="abId"]'
export const SORT_SELECTOR = 'button[title="Sort"]'
export const TOP_BUTTONS_SELECTOR= 'button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium' 
export const ACCOUNT_SUBMENU_SELECTOR= 'ul.MuiList-padding'
export const ACCOUNT_SUBMENU_ITEMS_SELECTOR= 'li.MuiMenuItem-gutters'
