# Generated by Django 4.0.6 on 2022-08-29 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_column='ab_target', max_length=512, unique=True)),
                ('species', models.TextField(db_column='target_species')),
                ('entrez_id', models.CharField(db_column='ab_target_entrez_gid', max_length=32, unique=True)),
                ('subregion', models.CharField(db_column='target_subregion', max_length=512)),
                ('modifications', models.TextField(db_column='target_modification')),
                ('epitope', models.CharField(max_length=128)),
                ('uniprot_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(db_column='vendor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='vendor', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Antibody',
            fields=[
                ('ab_name', models.TextField()),
                ('ab_id', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('accession', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1)])),
                ('ix', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('commercial_type', models.CharField(choices=[('CM', 'commercial'), ('PS', 'personal'), ('NP', 'non-profit'), ('OT', 'other')], default='OT', max_length=2)),
                ('catalog_num', models.CharField(max_length=512)),
                ('cat_alt', models.TextField()),
                ('url', models.URLField()),
                ('source_organism', models.CharField(max_length=128)),
                ('clonality', models.CharField(choices=[('UNK', 'Unknown'), ('CKT', 'Cocktail'), ('CTR', 'Control'), ('I_CTR', 'Isotype Control'), ('MNC', 'Monoclonal'), ('MNC_S', 'Monoclonal Secondary'), ('PLC', 'Polyclonal'), ('PLC_S', 'Polyclonal Secondary'), ('OLC', 'Oligoclonal'), ('RCB', 'Recombinant'), ('RCB_M', 'Recombinant Monoclonal'), ('RCB_M_S', 'Recombinant Monoclonal Secondary'), ('RCB_P', 'Recombinant Polyclonal'), ('RCB_P_S', 'Recombinant Polyclonal Secondary')], default='UNK', max_length=7)),
                ('clone_id', models.CharField(max_length=32)),
                ('product_isotype', models.CharField(choices=[('IGG', 'IgG'), ('IGG1', 'IgG1'), ('IGG2', 'IgG2'), ('IGG3', 'IgG3'), ('IGG4', 'IgG4'), ('IGY', 'IgY'), ('IGA', 'IgA'), ('IGM', 'IgM')], max_length=4)),
                ('product_conjugate', models.CharField(max_length=32)),
                ('defining_citation', models.CharField(max_length=512)),
                ('product_form', models.CharField(choices=[('LP', 'Lyophilized'), ('AP', 'Affinity Purified'), ('LQ', 'LIQUID')], max_length=2)),
                ('comments', models.TextField()),
                ('feedback', models.TextField()),
                ('curator_comment', models.TextField()),
                ('disc_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('C', 'Curated'), ('R', 'Rejected'), ('Q', 'QUEUE')], default='Q', max_length=1)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('curate_time', models.DateTimeField(auto_now=True)),
                ('antigen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.antigen')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.vendor')),
            ],
        ),
    ]
