# Generated by Django 4.0.6 on 2022-09-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_column='ab_target', max_length=512)),
                ('entrez_id', models.CharField(db_column='ab_target_entrez_gid', max_length=1024, unique=True)),
                ('uniprot_id', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='vendor', max_length=256)),
                ('nif_id', models.CharField(db_column='nif_id', max_length=32)),
                ('commercial_type', models.CharField(choices=[('commercial', 'commercial'), ('personal', 'personal'), ('non-profit', 'non-profit'), ('other', 'other')], default='other', max_length=128)),
                ('synonyms', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(db_column='domain_name', null=True, unique=True)),
                ('is_domain_visible', models.BooleanField(db_column='link', default=True)),
                ('status', models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], default='QUEUE', max_length=32)),
                ('vendor', models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Antibody',
            fields=[
                ('ix', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ab_name', models.CharField(max_length=512)),
                ('ab_id', models.CharField(max_length=32, unique=True)),
                ('accession', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=32)),
                ('catalog_num', models.CharField(max_length=64)),
                ('cat_alt', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=512)),
                ('species', models.CharField(db_column='target_species', max_length=1024)),
                ('subregion', models.CharField(db_column='target_subregion', max_length=32)),
                ('modifications', models.CharField(db_column='target_modification', max_length=64)),
                ('epitope', models.CharField(max_length=128)),
                ('source_organism', models.CharField(max_length=64)),
                ('clonality', models.CharField(choices=[('unknown', 'Unknown'), ('cocktail', 'Cocktail'), ('control', 'Control'), ('isotype control', 'Isotype Control'), ('monoclonal', 'Monoclonal'), ('monoclonal secondary', 'Monoclonal Secondary'), ('polyclonal', 'Polyclonal'), ('polyclonal secondary', 'Polyclonal Secondary'), ('oligoclonal', 'Oligoclonal'), ('recombinant', 'Recombinant'), ('recombinant monoclonal', 'Recombinant Monoclonal'), ('recombinant monoclonal secondary', 'Recombinant Monoclonal Secondary'), ('recombinant polyclonal', 'Recombinant Polyclonal'), ('recombinant polyclonal secondary', 'Recombinant Polyclonal Secondary')], default='unknown', max_length=255)),
                ('clone_id', models.CharField(max_length=256)),
                ('product_isotype', models.CharField(max_length=256)),
                ('product_conjugate', models.CharField(max_length=128)),
                ('defining_citation', models.CharField(max_length=2048)),
                ('product_form', models.CharField(max_length=512)),
                ('comments', models.TextField()),
                ('feedback', models.TextField()),
                ('curator_comment', models.TextField()),
                ('disc_date', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], default='QUEUE', max_length=32)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('curate_time', models.DateTimeField(auto_now=True)),
                ('antigen', models.ForeignKey(db_column='antigen_id', on_delete=django.db.models.deletion.RESTRICT, to='api.antigen')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.vendor')),
            ],
        ),
    ]
