# Generated by Django 4.0.6 on 2022-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
