# Generated by Django 4.0.6 on 2022-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='commercial_type',
        ),
        migrations.AddField(
            model_name='antibody',
            name='commercial_type',
            field=models.CharField(choices=[('commercial', 'commercial'), ('personal', 'personal'), ('non-profit', 'non-profit'), ('other', 'other')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
