# Generated by Django 4.0.6 on 2022-09-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibody',
            name='commercial_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='commercial_type',
            field=models.CharField(choices=[('CM', 'commercial'), ('PS', 'personal'), ('NP', 'non-profit'), ('OT', 'other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nif_id',
            field=models.CharField(db_column='nifID', default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='synonyms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='accession',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_form',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VendorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(db_column='domain_name', null=True, unique=True)),
                ('is_domain_visible', models.BooleanField(db_column='link', default=True)),
                ('status', models.CharField(choices=[('C', 'Curated'), ('R', 'Rejected'), ('Q', 'QUEUE')], default='Q', max_length=1)),
                ('vendor', models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.vendor')),
            ],
        ),
    ]
