# Generated by Django 4.0.6 on 2022-09-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.CreateModel(
            name='VendorSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
        ),
    ]
