# Generated by Django 4.0.6 on 2022-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_antibody_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='cat_alt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
