# Generated by Django 4.0.6 on 2022-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_antibody_status_alter_vendordomain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigen',
            name='symbol',
            field=models.CharField(db_column='ab_target', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='antigen',
            constraint=models.UniqueConstraint(fields=('symbol', 'species'), name='unique_catalog_num_per_vendor'),
        ),
    ]
