# Generated by Django 4.0.6 on 2022-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_antibody_modifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='epitope',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
