# Generated by Django 4.0.6 on 2022-09-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_antigen_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntibodyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.TextField(db_column='target_species')),
                ('subregion', models.CharField(db_column='target_subregion', max_length=512)),
                ('modifications', models.TextField(db_column='target_modification')),
                ('epitope', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='antigen',
            name='unique_catalog_num_per_vendor',
        ),
        migrations.RemoveField(
            model_name='antibody',
            name='antigen',
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='epitope',
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='modifications',
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='species',
        ),
        migrations.RemoveField(
            model_name='antigen',
            name='subregion',
        ),
        migrations.AlterField(
            model_name='antigen',
            name='symbol',
            field=models.CharField(db_column='ab_target', max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='antibodytarget',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.antigen'),
        ),
        migrations.AddField(
            model_name='antibody',
            name='target',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.RESTRICT, to='api.antibodytarget'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='antibodytarget',
            constraint=models.UniqueConstraint(fields=('antigen', 'species'), name='unique_antigen_species'),
        ),
    ]
