# Generated by Django 4.0.6 on 2022-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_antibodytarget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigen',
            name='entrez_id',
            field=models.CharField(db_column='ab_target_entrez_gid', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='antigen',
            name='uniprot_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
