# Generated by Django 4.0.6 on 2022-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_antibody_clone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='product_conjugate',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
