# Generated by Django 4.0.6 on 2022-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_antigen_entrez_id_alter_antigen_uniprot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigen',
            name='entrez_id',
            field=models.CharField(blank=True, db_column='ab_target_entrez_gid', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='antigen',
            name='uniprot_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
