# Generated by Django 4.0.6 on 2022-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_antibody_product_conjugate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='defining_citation',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
