# Generated by Django 4.0.6 on 2022-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_antibody_defining_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='product_form',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
