# Generated by Django 4.0.6 on 2022-09-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_antigen_entrez_id_alter_antigen_uniprot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='cat_alt',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='catalog_num',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clone_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='defining_citation',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='disc_date',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_conjugate',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_form',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_isotype',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='source_organism',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='antibodytarget',
            name='modifications',
            field=models.CharField(db_column='target_modification', max_length=64),
        ),
        migrations.AlterField(
            model_name='antibodytarget',
            name='species',
            field=models.CharField(db_column='target_species', max_length=1024),
        ),
        migrations.AlterField(
            model_name='antibodytarget',
            name='subregion',
            field=models.CharField(db_column='target_subregion', max_length=32),
        ),
        migrations.AlterField(
            model_name='antigen',
            name='entrez_id',
            field=models.CharField(db_column='ab_target_entrez_gid', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antigen',
            name='uniprot_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_column='vendor', max_length=256),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='synonyms',
            field=models.CharField(max_length=512),
        ),
    ]
