# Generated by Django 4.0.6 on 2022-09-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_antibody_product_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
