# Generated by Django 4.0.6 on 2022-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_antibody_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='curator_comment',
            field=models.TextField(null=True),
        ),
    ]
