# Generated by Django 4.0.6 on 2022-09-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_antibody_ab_name_alter_antibody_cat_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigen',
            name='uniprot_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
