# Generated by Django 4.0.6 on 2022-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_antigen_uniprot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
