# Generated by Django 4.0.6 on 2022-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_antibody_curator_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='disc_date',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
