# Generated by Django 4.0.6 on 2022-09-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_antibody_disc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='source_organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source', to='api.specie'),
        ),
    ]
