# Generated by Django 4.0.6 on 2022-09-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_antibody_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
