# Generated by Django 4.0.6 on 2022-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_antibody_source_organism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
