# Generated by Django 4.0.6 on 2022-09-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_antibody_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibody',
            name='target',
        ),
        migrations.AddField(
            model_name='antibody',
            name='antigen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='api.antigen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antibody',
            name='epitope',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antibody',
            name='modifications',
            field=models.CharField(db_column='target_modification', default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antibody',
            name='species',
            field=models.CharField(db_column='target_species', default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antibody',
            name='subregion',
            field=models.CharField(db_column='target_subregion', default='', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AntibodyTarget',
        ),
    ]
