# Generated by Django 4.0.6 on 2022-09-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_antibody_target_antibody_antigen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='antigen',
            field=models.ForeignKey(db_column='antigen_id', on_delete=django.db.models.deletion.RESTRICT, to='api.antigen'),
        ),
    ]
