# Generated by Django 4.0.6 on 2022-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_antibody_antigen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
