# Generated by Django 4.0.6 on 2022-09-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_antibody_product_isotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antigen',
            name='entrez_id',
            field=models.CharField(db_column='ab_target_entrez_gid', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antigen',
            name='uniprot_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
