# Generated by Django 4.0.6 on 2022-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_antigen_entrez_id_alter_antigen_uniprot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='catalog_num',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
