# Generated by Django 4.0.6 on 2022-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_antibody_catalog_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
