# Generated by Django 4.0.6 on 2022-09-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_antibody_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
