# Generated by Django 4.0.6 on 2022-10-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='antibody',
            options={'verbose_name_plural': 'antibodies'},
        ),
        migrations.RemoveField(
            model_name='antibody',
            name='applications',
        ),
        migrations.AlterField(
            model_name='antibody',
            name='cat_alt',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clonality',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('cocktail', 'Cocktail'), ('control', 'Control'), ('isotype control', 'Isotype Control'), ('monoclonal', 'Monoclonal'), ('monoclonal secondary', 'Monoclonal Secondary'), ('polyclonal', 'Polyclonal'), ('polyclonal secondary', 'Polyclonal Secondary'), ('oligoclonal', 'Oligoclonal'), ('recombinant', 'Recombinant'), ('recombinant monoclonal', 'Recombinant Monoclonal'), ('recombinant monoclonal secondary', 'Recombinant Monoclonal Secondary'), ('recombinant polyclonal', 'Recombinant Polyclonal'), ('recombinant polyclonal secondary', 'Recombinant Polyclonal Secondary')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clone_id',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='comments',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='curator_comment',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='defining_citation',
            field=models.CharField(db_index=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='disc_date',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='epitope',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='feedback',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='kit_contents',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='modifications',
            field=models.CharField(db_column='target_modification', db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_conjugate',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_form',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_isotype',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='subregion',
            field=models.CharField(db_column='target_subregion', db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='url',
            field=models.URLField(db_index=True, max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='AntibodyApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.antibody')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
        ),
        migrations.AddField(
            model_name='antibody',
            name='applications',
            field=models.ManyToManyField(through='api.AntibodyApplications', to='api.application'),
        ),
    ]
