# Generated by Django 4.0.6 on 2022-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(db_column='ab_target', max_length=1024, null=True),
        ),
    ]
