# Generated by Django 4.1.4 on 2022-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="target_species_raw",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
