# Generated by Django 4.1.4 on 2023-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="ab_target",
            field=models.CharField(
                blank=True,
                db_column="ab_target",
                db_index=True,
                max_length=1024,
                null=True,
            ),
        ),
    ]
