# Generated by Django 4.0.6 on 2022-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='commercial_type',
            field=models.CharField(choices=[('commercial', 'commercial'), ('personal', 'personal'), ('non-profit', 'non-profit'), ('other', 'other')], default='other', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='eu_id',
            field=models.CharField(db_column='euid', max_length=255, null=True),
        ),
    ]
