# Generated by Django 4.0.6 on 2022-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_antibody_antigen_alter_antibody_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibody',
            name='uid_legacy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
