# Generated by Django 4.0.6 on 2022-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendor_commercial_type_vendor_eu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
