# Generated by Django 4.1.4 on 2022-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_antibody_target_species_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="defining_citation",
            field=models.CharField(blank=True, max_length=16384, null=True),
        ),
    ]
