# Generated by Django 4.0.6 on 2022-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application_alter_antibody_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibody',
            name='lastedit_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='curate_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
