# Generated by Django 4.0.6 on 2022-09-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gene_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='entrez_id',
            field=models.CharField(db_column='ab_target_entrez_gid', max_length=2048, null=True),
        ),
    ]
