# Generated by Django 4.0.6 on 2022-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_antibody_uid_legacy_alter_antibody_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='ab_name',
            field=models.CharField(db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='catalog_num',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='curate_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='species',
            field=models.ManyToManyField(db_column='target_species', related_name='targets', through='api.AntibodySpecies', to='api.specie'),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], db_index=True, default='QUEUE', max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
