# Generated by Django 4.1.5 on 2023-01-20 08:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_antibody_defining_citation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx",
        ),
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx2",
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "ab_name",
                        "clone_id__normalize_relaxed",
                        config="english",
                        weight="A",
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "accession",
                        "commercial_type",
                        "uid_legacy",
                        "url",
                        "subregion",
                        "modifications",
                        "epitope",
                        "clonality",
                        "product_isotype",
                        "product_conjugate",
                        "defining_citation",
                        "product_form",
                        "comments",
                        "kit_contents",
                        "feedback",
                        "curator_comment",
                        "disc_date",
                        "status",
                        config="english",
                        weight="C",
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                name="antibody_all_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "accession",
                    "commercial_type",
                    "uid_legacy",
                    "url",
                    "subregion",
                    "modifications",
                    "epitope",
                    "clonality",
                    "product_isotype",
                    "product_conjugate",
                    "defining_citation",
                    "product_form",
                    "comments",
                    "kit_contents",
                    "feedback",
                    "curator_comment",
                    "disc_date",
                    "status",
                    config="english",
                    weight="C",
                ),
                name="antibody_all_fts_idx2",
            ),
        ),
    ]
