# Generated by Django 4.0.6 on 2022-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_antibody_lastedit_time_alter_antibody_curate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='curate_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
