# Generated by Django 4.0.6 on 2022-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gene_entrez_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=32),
        ),
    ]
