# Generated by Django 4.1.4 on 2023-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_antibody_antigen_alter_antibody_ab_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="uniprot_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
