# Generated by Django 4.1.4 on 2022-12-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_antibody_insert_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="accession",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="applications",
            field=models.ManyToManyField(
                blank=True, through="api.AntibodyApplications", to="api.application"
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="cat_alt",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="clonality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Unknown"),
                    ("cocktail", "Cocktail"),
                    ("control", "Control"),
                    ("isotype control", "Isotype Control"),
                    ("monoclonal", "Monoclonal"),
                    ("monoclonal secondary", "Monoclonal Secondary"),
                    ("polyclonal", "Polyclonal"),
                    ("polyclonal secondary", "Polyclonal Secondary"),
                    ("oligoclonal", "Oligoclonal"),
                    ("recombinant", "Recombinant"),
                    ("recombinant monoclonal", "Recombinant Monoclonal"),
                    (
                        "recombinant monoclonal secondary",
                        "Recombinant Monoclonal Secondary",
                    ),
                    ("recombinant polyclonal", "Recombinant Polyclonal"),
                    (
                        "recombinant polyclonal secondary",
                        "Recombinant Polyclonal Secondary",
                    ),
                ],
                db_index=True,
                default="unknown",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="clone_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="curate_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="curator_comment",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="defining_citation",
            field=models.CharField(
                blank=True, db_index=True, max_length=16384, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="disc_date",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="epitope",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="feedback",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="kit_contents",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="modifications",
            field=models.CharField(
                blank=True,
                db_column="target_modification",
                db_index=True,
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="product_conjugate",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="product_form",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="product_isotype",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="source_organism",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="source",
                to="api.specie",
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                db_column="target_species",
                related_name="targets",
                through="api.AntibodySpecies",
                to="api.specie",
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="subregion",
            field=models.CharField(
                blank=True,
                db_column="target_subregion",
                db_index=True,
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="uid_legacy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="url",
            field=models.URLField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="eu_id",
            field=models.CharField(
                blank=True, db_column="euid", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="nif_id",
            field=models.CharField(
                blank=True, db_column="nif_id", max_length=32, null=True
            ),
        ),
    ]
