# Generated by Django 4.0.6 on 2022-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_antibody_ab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='accession',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], default='QUEUE', max_length=8),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='subregion',
            field=models.CharField(db_column='target_subregion', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vendordomain',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], default='QUEUE', max_length=8),
        ),
    ]
