# Generated by Django 4.0.6 on 2022-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_antibody_ab_id_alter_antibody_ab_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='entrez_id',
            field=models.CharField(db_column='ab_target_entrez_gid', db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(db_column='ab_target', db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='uniprot_id',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_column='vendor', db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='vendordomain',
            name='base_url',
            field=models.URLField(db_column='domain_name', db_index=True, max_length=2048, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendordomain',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued')], db_index=True, default='QUEUE', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorsynonym',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
