# Generated by Django 4.1.4 on 2022-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_antibody_accession_alter_antibody_applications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="entrez_id",
            field=models.CharField(
                blank=True,
                db_column="ab_target_entrez_gid",
                db_index=True,
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="uniprot_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
