# Generated by Django 4.1.3 on 2023-01-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_antibody_submitter"),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE api_antibody SET submitter_id = (
            SELECT user_id FROM cloudharness_django_member
            WHERE kc_id = uid
        ) WHERE uid <> '';"""
        ),
    ]
