# Generated by Django 4.1.5 on 2023-01-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_remove_antibody_antibody_all_fts_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="antibody",
            old_name="uid",
            new_name="uid_tmp",
        ),
        migrations.AddField(
            model_name="antibody",
            name="uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
