# Generated by Django 4.0.6 on 2023-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_antibody_lastedit_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibody',
            name='target_species_raw',
        ),
    ]
