# Generated by Django 4.1.4 on 2022-12-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_antibody_uid_alter_gene_entrez_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gene",
            new_name="Antigen",
        ),
    ]
