# Generated by Django 4.1.4 on 2023-02-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_antibody_target_species_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="antigen",
            field=models.ForeignKey(
                db_column="antigen_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.antigen",
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="vendor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.vendor"
            ),
        ),
    ]
