# Generated by Django 4.0.6 on 2022-09-30 22:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gene_entrez_id_alter_gene_symbol_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='antibody',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('catalog_num__normalize', 'cat_alt__normalize_relaxed', config='english'), name='antibody_catalog_num_fts_idx'),
        ),
    ]
