# Generated by Django 4.1.3 on 2023-01-19 18:39

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_update_submitters_from_kc_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx",
        ),
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx2",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="submitter",
        ),
        migrations.AlterField(
            model_name="antibody",
            name="uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "ab_name",
                        "clone_id__normalize_relaxed",
                        config="english",
                        weight="A",
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "accession",
                        "commercial_type",
                        "uid_legacy",
                        "url",
                        "subregion",
                        "modifications",
                        "epitope",
                        "clonality",
                        "product_isotype",
                        "product_conjugate",
                        "defining_citation",
                        "product_form",
                        "comments",
                        "kit_contents",
                        "feedback",
                        "curator_comment",
                        "disc_date",
                        "status",
                        config="english",
                        weight="C",
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                name="antibody_all_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "accession",
                    "commercial_type",
                    "uid_legacy",
                    "url",
                    "subregion",
                    "modifications",
                    "epitope",
                    "clonality",
                    "product_isotype",
                    "product_conjugate",
                    "defining_citation",
                    "product_form",
                    "comments",
                    "kit_contents",
                    "feedback",
                    "curator_comment",
                    "disc_date",
                    "status",
                    config="english",
                    weight="C",
                ),
                name="antibody_all_fts_idx2",
            ),
        ),
    ]
