# Generated by Django 4.1.5 on 2023-01-20 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_antibody_uid_tmp_alter_antibody_uid"),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE api_antibody SET uid_id = (
            SELECT user_id FROM cloudharness_django_member
            WHERE kc_id = uid_tmp
        ) WHERE uid_tmp <> '';"""
        ),
    ]
