# Generated by Django 4.1.4 on 2023-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_antibody_accession_alter_antibody_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
