# Generated by Django 4.0.6 on 2022-09-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_antibody_disc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='disc_date',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
