# Generated by Django 4.0.6 on 2022-09-30 23:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_antibody_antibody_catalog_num_fts_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='antibody',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('ab_name', 'clone_id__normalize_relaxed', config='english'), name='antibody_names_fts_idx'),
        ),
        migrations.AddIndex(
            model_name='antibody',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('ab_id', 'accession', 'commercial_type', 'uid', 'uid_legacy', 'url', 'subregion', 'modifications', 'epitope', 'source_organism', 'clonality', 'product_isotype', 'product_conjugate', 'defining_citation', 'product_form', 'comments', 'applications', 'kit_contents', 'feedback', 'curator_comment', 'disc_date', 'status', config='english'), name='antibody_all_fts_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('symbol', config='english'), name='gene_symbol_fts_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='english'), name='vendor_name_fts_idx'),
        ),
    ]
