# Generated by Django 4.1.5 on 2023-01-20 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_auto_20230120_0839"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antibody",
            name="uid_tmp",
        ),
    ]
