# Generated by Django 4.1.4 on 2023-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_vendordomain_vendor"),
    ]

    operations = [
    
    ]
