# Generated by Django 4.1.4 on 2023-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_vendordomain_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(
                db_column="vendor", db_index=True, max_length=512, unique=True
            ),
        ),
    ]
