# Generated by Django 4.2.9 on 2024-02-15 12:59

from django.db import migrations, connection
from cloudharness import log
from api.repositories.maintainance import rechunk_catalog_number

def chunk_catalog_number(apps, schema_editor):
    Antibody = apps.get_model('api', 'Antibody')
    rechunk_catalog_number(Antibody)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_antibody_comments"),
    ]
    operations = [
        migrations.RunPython(chunk_catalog_number)
    ]
