# Generated by Django 4.2.9 on 2024-02-15 12:59

from django.db import migrations
from api.utilities.functions import catalog_number_chunked


def rechunk_catalog_number(apps, schema_editor):
    Antibody = apps.get_model('api', 'Antibody')
    for antibody in Antibody.objects.all():
        antibody.catalog_num_search = catalog_number_chunked(antibody.catalog_num, antibody.cat_alt)
        antibody.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_antibody_comments"),
    ]

    operations = [
        migrations.RunPython(rechunk_catalog_number)
    ]
