# Generated by Django 4.0.6 on 2022-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_antibody_disc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='accession',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='cat_alt',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='catalog_num',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='clonality',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('cocktail', 'Cocktail'), ('control', 'Control'), ('isotype control', 'Isotype Control'), ('monoclonal', 'Monoclonal'), ('monoclonal secondary', 'Monoclonal Secondary'), ('polyclonal', 'Polyclonal'), ('polyclonal secondary', 'Polyclonal Secondary'), ('oligoclonal', 'Oligoclonal'), ('recombinant', 'Recombinant'), ('recombinant monoclonal', 'Recombinant Monoclonal'), ('recombinant monoclonal secondary', 'Recombinant Monoclonal Secondary'), ('recombinant polyclonal', 'Recombinant Polyclonal'), ('recombinant polyclonal secondary', 'Recombinant Polyclonal Secondary')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='commercial_type',
            field=models.CharField(choices=[('commercial', 'commercial'), ('personal', 'personal'), ('non-profit', 'non-profit'), ('other', 'other')], default='other', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='defining_citation',
            field=models.CharField(max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='epitope',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='modifications',
            field=models.CharField(db_column='target_modification', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_conjugate',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='product_form',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='subregion',
            field=models.CharField(db_column='target_subregion', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='antibody',
            name='uid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_column='vendor', max_length=512),
        ),
        migrations.AlterField(
            model_name='vendorsynonym',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
