# Generated by Django 4.1.4 on 2023-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_vendor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="target_species_raw",
            field=models.CharField(
                blank=True,
                help_text="Comma separated value for target species. Values filled here will be parsed and assigned to the 'Target species' field.",
                max_length=4096,
                null=True,
                verbose_name="Target species (csv)",
            ),
        ),
    ]
