# Generated by Django 4.0.6 on 2022-09-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_antibody_ab_id_alter_antibody_accession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='accession',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
