# Generated by Django 4.0.6 on 2023-02-15 15:55

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_antibody_target_species_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntibodyFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to=api.models.antibody_persistence_directory)),
                ('display_name', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploader_uid', models.CharField(max_length=256)),
                ('filehash', models.CharField(max_length=32)),
                ('antibody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.antibody')),
            ],
        ),
    ]
