# Generated by Django 4.0.6 on 2022-09-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_antibody_accession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='antigen',
            field=models.ForeignKey(db_column='antigen_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.gene'),
        ),
    ]
