# Generated by Django 4.0.6 on 2023-02-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_antibodyfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibodyfiles',
            name='antibody',
            field=models.ForeignKey(db_column='ab_ix', on_delete=django.db.models.deletion.CASCADE, to='api.antibody'),
        ),
    ]
