# Generated by Django 4.2.9 on 2024-04-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240315_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued'), ('UNDER_REVIEW', 'Under Review')], db_index=True, default='QUEUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='vendordomain',
            name='status',
            field=models.CharField(choices=[('CURATED', 'Curated'), ('REJECTED', 'Rejected'), ('QUEUE', 'Queued'), ('UNDER_REVIEW', 'Under Review')], db_index=True, default='QUEUE', max_length=12),
        ),
    ]
