# Generated by Django 4.0.6 on 2022-09-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_antibody_antigen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibody',
            name='ab_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
