# Generated by Django 4.1.4 on 2023-03-10 12:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_vendor_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntibodyFiles",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("type", models.CharField(max_length=32)),
                (
                    "file",
                    models.FileField(
                        upload_to=api.models.antibody_persistence_directory
                    ),
                ),
                ("display_name", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("uploader_uid", models.CharField(max_length=256)),
                ("filehash", models.CharField(max_length=32)),
                (
                    "antibody",
                    models.ForeignKey(
                        db_column="ab_ix",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.antibody",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Antibody files",
            },
        ),
    ]
