# Generated by Django 4.1.4 on 2023-03-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_antibodyfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="ab_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="antigen",
            field=models.ForeignKey(
                blank=True,
                db_column="antigen_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.antigen",
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="catalog_num",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="antibody",
            name="commercial_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial", "commercial"),
                    ("personal", "personal"),
                    ("non-profit", "non-profit"),
                    ("other", "other"),
                ],
                default="other",
                max_length=10,
                null=True,
            ),
        ),
    ]
