# Generated by Django 4.0.6 on 2023-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_antibodyfiles_antibody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(db_column='vendor', db_index=True, max_length=512),
        ),
    ]
