# Generated by Django 4.1.4 on 2023-03-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_antibody_ab_name_alter_antibody_antigen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.vendor",
            ),
        ),
    ]
