# Generated by Django 4.2.9 on 2024-05-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_status_field_antibody_vendordomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibody',
            name='citation',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        )
    ]
