# Generated by Django 4.1.4 on 2023-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_antibody_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="commercial_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial", "commercial"),
                    ("personal", "personal"),
                    ("non-profit", "non-profit"),
                    ("other", "other"),
                ],
                default="other",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="commercial_type",
            field=models.CharField(
                choices=[
                    ("commercial", "commercial"),
                    ("personal", "personal"),
                    ("non-profit", "non-profit"),
                    ("other", "other"),
                ],
                default="other",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendordomain",
            name="base_url",
            field=models.URLField(
                db_column="domain_name", db_index=True, max_length=2048, null=True
            ),
        ),
    ]
