# Generated by Django 4.1.4 on 2023-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_antibody_commercial_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="show_link",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="show_link",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
