# Generated by Django 4.1.4 on 2023-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_antibody_show_link_vendor_show_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antigen",
            name="entrez_id",
        ),
        migrations.RemoveField(
            model_name="antigen",
            name="uniprot_id",
        ),
        migrations.AddField(
            model_name="antibody",
            name="entrez_id",
            field=models.CharField(
                blank=True,
                db_column="ab_target_entrez_gid",
                db_index=True,
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="uniprot_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
