# Generated by Django 4.2.10 on 2025-07-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_auto_20250103_0311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="uid_legacy",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalantibody",
            name="uid_legacy",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalvendor",
            name="eu_id",
            field=models.CharField(
                blank=True, db_column="euid", db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalvendor",
            name="nif_id",
            field=models.CharField(
                blank=True, db_column="nif_id", db_index=True, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="eu_id",
            field=models.CharField(
                blank=True, db_column="euid", db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="nif_id",
            field=models.CharField(
                blank=True, db_column="nif_id", db_index=True, max_length=32, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=models.Index(
                models.Func("catalog_num", function="LOWER"),
                models.F("vendor_id"),
                name="antibody_catalog_num_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=models.Index(
                models.Func("catalog_num", function="UPPER"),
                models.F("vendor_id"),
                name="antibody_catalog_num_upper_idx",
            ),
        ),
    ]
