# Generated by Django 4.1.4 on 2023-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_antigen_entrez_id_remove_antigen_uniprot_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibodyfiles",
            name="type",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
