# Generated by Django 4.1.4 on 2023-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_antibodyfiles_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibodyfiles",
            name="type",
            field=models.CharField(default="mds", max_length=32, null=True),
        ),
    ]
