# Generated by Django 5.2.7 on 2025-11-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_search_duplicates_index'),
    ]

    operations = [
         migrations.CreateModel(
            name='AntibodyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=12, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Antibody Statistics',
                'db_table': 'api_antibody_stats',
            },
        )
    ]
