# Generated by manual migration for initializing antibody stats

from django.db import migrations


def populate_antibody_stats(apps, schema_editor):
    """Initialize the antibody stats table with CURATED count only"""
    # Reuse the existing refresh function from maintenance
    from api.repositories.maintainance import refresh_antibody_stats
    refresh_antibody_stats()


def reverse_populate(apps, schema_editor):
    """Clear the stats table"""
    AntibodyStats = apps.get_model('api', 'AntibodyStats')
    db_alias = schema_editor.connection.alias
    AntibodyStats.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_antibodystats_remove_antibodysearch_citations_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_antibody_stats, reverse_populate),
    ]
