# Generated by Django 4.1.4 on 2023-05-04 10:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_antibody_show_link_alter_vendor_show_link"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_catalog_num_fts_idx",
        ),
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx",
        ),
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx2",
        ),
        migrations.AddField(
            model_name="antibody",
            name="catalog_num_search",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "catalog_num_search", config="english"
                ),
                name="antibody_catalog_num_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "ab_name",
                        "clone_id__normalize_relaxed",
                        config="english",
                        weight="A",
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "accession",
                        "subregion",
                        "modifications",
                        "epitope",
                        "product_isotype",
                        "product_conjugate",
                        "defining_citation",
                        "product_form",
                        "comments",
                        "kit_contents",
                        "feedback",
                        "curator_comment",
                        "disc_date",
                        "status",
                        "vendor",
                        "antigen",
                        "source_organism",
                        config="english",
                        weight="C",
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                name="antibody_all_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "accession",
                    "commercial_type",
                    "url",
                    "subregion",
                    "modifications",
                    "epitope",
                    "clonality",
                    "product_isotype",
                    "product_conjugate",
                    "defining_citation",
                    "product_form",
                    "comments",
                    "kit_contents",
                    "feedback",
                    "curator_comment",
                    "disc_date",
                    "status",
                    config="english",
                    weight="C",
                ),
                name="antibody_all_fts_idx2",
            ),
        ),
    ]
