# Generated by Django 4.1.4 on 2023-05-04 18:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_antibody_antibody_catalog_num_fts_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_all_fts_idx2",
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "accession",
                    "subregion",
                    "modifications",
                    "epitope",
                    "product_isotype",
                    "product_conjugate",
                    "defining_citation",
                    "product_form",
                    "comments",
                    "kit_contents",
                    "feedback",
                    "curator_comment",
                    "disc_date",
                    "status",
                    config="english",
                    weight="C",
                ),
                name="antibody_all_fts_idx2",
            ),
        ),
    ]
