# Generated by Django 4.1.4 on 2023-05-05 17:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_antibody_antibody_all_fts_idx2_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="antibody",
            name="antibody_catalog_num_fts_idx",
        ),
        migrations.AddIndex(
            model_name="antibody",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "catalog_num_search", config="simple"
                ),
                name="antibody_catalog_num_fts_idx",
            ),
        ),
    ]
